import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/panelEstudiantes")
public class PanelEstudiantesServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        response.setContentType("text/html; charset=UTF-8");
        PrintWriter out = response.getWriter();
        out.println("<!DOCTYPE html>");
        out.println("<html lang=\"es\">");
        out.println("<head>");
        out.println("  <meta charset=\"UTF-8\" />");
        out.println("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>");
        out.println("  <title>Panel de Estudiantes • Admin</title>");
        out.println("  <link rel=\"stylesheet\" href=\"estilosPEA.css\" />");
        out.println("  <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap\" rel=\"stylesheet\">");
        out.println("</head>");
        out.println("<body>");
        out.println("  <!-- Navegación superior -->");
        out.println("  <header class=\"navbar\">");
        out.println("    <h1 class=\"logo\">Administración</h1>");
        out.println("    <nav>");
        out.println("      <ul>");
        out.println("        <li><a href=\"gestionOficiales\">Oficiales</a></li>");
        out.println("        <li class=\"active\"><a href=\"#\">Estudiantes</a></li>");
        out.println("      </ul>");
        out.println("    </nav>");
        out.println("  </header>");
        out.println("");
        out.println("  <main class=\"container\">");
        out.println("    <div class=\"main-content\">");
        out.println("      <!-- Sección del formulario -->");
        out.println("      <section class=\"form-section\">");
        out.println("        <h3>Gestión de Estudiantes</h3>");
        out.println("        <form id=\"form-estudiante\" action=\"http://localhost:8080/exam_parcial2_manuel_edgar/guardarEstudiante\" method=\"post\">");
        out.println("          <div class=\"form-group\">");
        out.println("            <label for=\"primerNombre\">Primer Nombre *</label>");
        out.println("            <input type=\"text\" id=\"primerNombre\" name=\"primerNombre\" required>");
        out.println("          </div>");
        out.println("          <div class=\"form-group\">");
        out.println("            <label for=\"segundoNombre\">Segundo Nombre (opcional)</label>");
        out.println("            <input type=\"text\" id=\"segundoNombre\" name=\"segundoNombre\">");
        out.println("          </div>");
        out.println("          <div class=\"form-group\">");
        out.println("            <label for=\"primerApellido\">Primer Apellido *</label>");
        out.println("            <input type=\"text\" id=\"primerApellido\" name=\"primerApellido\" required>");
        out.println("          </div>");
        out.println("          <div class=\"form-group\">");
        out.println("            <label for=\"segundoApellido\">Segundo Apellido *</label>");
        out.println("            <input type=\"text\" id=\"segundoApellido\" name=\"segundoApellido\" required>");
        out.println("          </div>");
        out.println("          <div class=\"form-group\">");
        out.println("            <label for=\"identificacion\">Número de identificación *</label>");
        out.println("            <input type=\"text\" id=\"identificacion\" name=\"identificacion\" required>");
        out.println("          </div>");
        out.println("          <div class=\"form-group\">");
        out.println("            <label for=\"fechaNacimiento\">Fecha de nacimiento *</label>");
        out.println("            <input type=\"date\" id=\"fechaNacimiento\" name=\"fechaNacimiento\" required>");
        out.println("          </div>");
        out.println("          <div class=\"form-group\">");
        out.println("            <label for=\"carnet\">Carnet estudiantil *</label>");
        out.println("            <input type=\"text\" id=\"carnet\" name=\"carnet\" required>");
        out.println("          </div>");
        out.println("          <div class=\"form-group\">");
        out.println("            <label for=\"nacionalidad\">Nacionalidad *</label>");
        out.println("            <select id=\"nacionalidad\" name=\"nacionalidad\" required>");
        out.println("              <option value=\"\">Seleccione...</option>");
        out.println("              <option value=\"nacional\">Nacional</option>");
        out.println("              <option value=\"extranjero\">Extranjero</option>");
        out.println("            </select>");
        out.println("          </div>");
        out.println("          <div class=\"form-group\">");
        out.println("            <label for=\"direccion\">Dirección (Distrito) *</label>");
        out.println("            <select id=\"direccion\" name=\"direccion\" required>");
        out.println("              <option value=\"\">Seleccione...</option>");
        out.println("              <option>Upala</option>");
        out.println("              <option>Aguas Claras</option>");
        out.println("              <option>San José de Upala</option>");
        out.println("              <option>Bijagua</option>");
        out.println("              <option>Delicias</option>");
        out.println("              <option>Dos Ríos</option>");
        out.println("              <option>Yolillal</option>");
        out.println("              <option>Canalete</option>");
        out.println("            </select>");
        out.println("          </div>");
        out.println("");
        out.println("          <!-- Botones de acción -->");
        out.println("          <div class=\"footer-buttons\">");
        out.println("            <button class=\"clear-button\" type=\"reset\">🧹 Limpiar</button>");
        out.println("            <button class=\"add-button\" type=\"submit\">💾 Guardar</button>");
        out.println("          </div>");
        out.println("          <div class=\"footer-buttons\">");
        out.println("            <button class=\"edit-button\" type=\"button\">✏️ Editar</button>");
        out.println("            <button class=\"delete-button\" type=\"button\">🗑️ Eliminar</button>");
        out.println("          </div>");
        out.println("        </form>");
        out.println("      </section>");
        out.println("");
        out.println("      <!-- Sección de tabla -->");
        out.println("      <section class=\"table-section\">");
        out.println("        <div class=\"form-group\">");
        out.println("          <input type=\"text\" id=\"buscarEstudiante\" placeholder=\"🔍 Buscar Estudiante…\">");
        out.println("        </div>");
        out.println("        <table>");
        out.println("          <thead>");
        out.println("            <tr>");
        out.println("              <th>Nombre completo</th>");
        out.println("              <th>Identificación</th>");
        out.println("              <th>Fecha de nacimiento</th>");
        out.println("              <th>Edad</th>");
        out.println("              <th>Nacionalidad</th>");
        out.println("              <th>Carnet</th>");
        out.println("              <th>Distrito</th>");
        out.println("            </tr>");
        out.println("          </thead>");
        out.println("          <tbody>");
        out.println("            <!-- filas dinámicas -->");
        out.println("          </tbody>");
        out.println("        </table>");
        out.println("      </section>");
        out.println("");
        out.println("    </div>");
        out.println("  </main>");
        out.println("");
        out.println("  <footer class=\"footer\">");
        out.println("    © 2025 Seguridad y Tecnología • Todos los derechos reservados");
        out.println("  </footer>");
        out.println("</body>");
        out.println("</html>");
    }
}